### ISSUE TITLE
URL fora.

### ISSUE THREAD

**Issue by raulmelo** [raphaelfabeni/ui-interactions#33]
Fala Rapha! Atualmente o links de UI interações esta fora do ar. 

![image](https://github.com/raphaelfabeni/ui-interactions/assets/8516551/7075cb41-3225-45cf-b9b4-9e6929bb35c2)

Parabéns pelo projeto mandou muito bem!

**Comment by raphaelfabeni** [comment]
Opa @raulmelo ! Valeu cara! Esse é antiguinho mas gostei muito de brincar com ele!
Acabei de arrumar!
Valeu!
